window.LOGO_FILES = Object.freeze([
  "HEX Lab logo - Horizontal - main.png",
  "HEX Lab logo - Icon - main.png",
  "PNG/Full Black/HEX Lab logo - Horizontal - Full Black.png",
  "PNG/Full Black/HEX Lab logo - Horizontal - Full Black@2x.png",
  "PNG/Full Black/HEX Lab logo - Horizontal - Full Black@4x.png",
  "PNG/Full Black/HEX Lab logo - Icon - Full Black.png",
  "PNG/Full Black/HEX Lab logo - Icon - Full Black@2x.png",
  "PNG/Full Black/HEX Lab logo - Icon - Full Black@4x.png",
  "PNG/Full Black/HEX Lab logo - Vertical - Full Black.png",
  "PNG/Full Black/HEX Lab logo - Vertical - Full Black@2x.png",
  "PNG/Full Black/HEX Lab logo - Vertical - Full Black@4x.png",
  "PNG/Full White/HEX Lab logo - Horizontal - Full White.png",
  "PNG/Full White/HEX Lab logo - Horizontal - Full White@2x.png",
  "PNG/Full White/HEX Lab logo - Horizontal - Full White@4x.png",
  "PNG/Full White/HEX Lab logo - Icon - Full White.png",
  "PNG/Full White/HEX Lab logo - Icon - Full White@2x.png",
  "PNG/Full White/HEX Lab logo - Icon - Full White@4x.png",
  "PNG/Full White/HEX Lab logo - Vertical - Full White.png",
  "PNG/Full White/HEX Lab logo - Vertical - Full White@2x.png",
  "PNG/Full White/HEX Lab logo - Vertical - Full White@4x.png",
  "PNG/Main White/HEX Lab logo - Horizontal - main White.png",
  "PNG/Main White/HEX Lab logo - Horizontal - main White@2x.png",
  "PNG/Main White/HEX Lab logo - Horizontal - main White@4x.png",
  "PNG/Main White/HEX Lab logo - Icon - main White.png",
  "PNG/Main White/HEX Lab logo - Icon - main White@2x.png",
  "PNG/Main White/HEX Lab logo - Icon - main White@4x.png",
  "PNG/Main White/HEX Lab logo - Vertical - main White.png",
  "PNG/Main White/HEX Lab logo - Vertical - main White@2x.png",
  "PNG/Main White/HEX Lab logo - Vertical - main White@4x.png",
  "PNG/Main/HEX Lab logo - Horizontal - main.png",
  "PNG/Main/HEX Lab logo - Horizontal - main@2x.png",
  "PNG/Main/HEX Lab logo - Horizontal - main@4x.png",
  "PNG/Main/HEX Lab logo - Icon - main.png",
  "PNG/Main/HEX Lab logo - Icon - main@2x.png",
  "PNG/Main/HEX Lab logo - Icon - main@4x.png",
  "PNG/Main/HEX Lab logo - Vertical - main.png",
  "PNG/Main/HEX Lab logo - Vertical - main@2x.png",
  "PNG/Main/HEX Lab logo - Vertical - main@4x.png",
  "SVG/HEX Lab logo - Horizontal - Full Black.svg",
  "SVG/HEX Lab logo - Horizontal - Full White.svg",
  "SVG/HEX Lab logo - Horizontal - main White.svg",
  "SVG/HEX Lab logo - Horizontal - main.svg",
  "SVG/HEX Lab logo - Icon - Full Black.svg",
  "SVG/HEX Lab logo - Icon - Full White.svg",
  "SVG/HEX Lab logo - Icon - main White.svg",
  "SVG/HEX Lab logo - Icon - main.svg",
  "SVG/HEX Lab logo - Vertical - Full Black.svg",
  "SVG/HEX Lab logo - Vertical - Full White.svg",
  "SVG/HEX Lab logo - Vertical - main White.svg",
  "SVG/HEX Lab logo - Vertical - main.svg",
]);
